### ISSUE TITLE
Avoid duplicate references in same Xcode "Group" following conflict resolution

### ISSUE THREAD

**Issue by pryder-fleetaero** [Lightricks/Kintsugi#75] opened 2022-07-01 00:51 UTC
Hi,

The tool has been working great and is a massive time saver (why is this level of conflict resolution not part of Xcode when it knows it's file format better than anyone...) so kudos to all involved 👍

I notice occasionally following conflict resolution (usually new files added to a different branch I believe) that I end up with multiple references to the same file within the same Xcode group which I usually have to go clean up.

Maybe there's a technical reason why it ends up this way (perhaps different UUIDs to the same file or something), however it seems it could be something that could be filtered out during the resolution process (is there ever a reason to have multiple references to the same file at the same group level in Xcode? Perhaps there is for more complex or nuanced projects than mine so this idea is invalid).

<img width="616" alt="image" src="https://user-images.githubusercontent.com/92766108/176800939-75800796-c912-453c-8a5d-8d0b2fd246b5.png">

<img width="322" alt="image" src="https://user-images.githubusercontent.com/92766108/176800991-6d1ca160-a0ee-4894-8e40-de1d96935c37.png">

Thanks!

**Comment by pryder-fleetaero** [comment] 2022-07-01 00:53
Oh I am guessing this is probably a duplicate of #6, so feel free to close if it is

**Comment by byohay** [comment] 2022-07-04 08:35
Hi @pryder-fleetaero! 
Right, it's a duplicate of #6. 
It's not that there's a technical reason that prevents us from creating duplicates, it's that Kintsugi can't know if you really meant to add the same file twice or not. Then again, I really can't think of a good reason to have the same file twice in the same group, which is why I opened the issue.
I think that eventually Kintsugi will try not to create duplicates by default, and will support creating them with a flag if someone wants to.

**Closed by byohay** 2022-07-04 08:35 UTC

**Comment by pryder-fleetaero** [comment] 2022-07-04 08:42
Thanks @byohay. Yeah I am sure someone might have multiple references in the same group in some strange style of managing targets or something but you’d have to assume it’s be rare, so the future idea of eliminating unless with a switch sounds like a great direction that’ll minimise cleanup work for the majority.
